; Frame Checker - Default Settings
; Copyright (C) 2025 Vuk Knežević
; This file is licensed under the terms of the GNU General Public License v3.0.
; See LICENSE or COPYING for full license details.

[app]
; Theme: Dark or Light - case insensitive
; defaults to Dark if no value is set 
theme = Dark 
; Default logs directory to save filters detections
; must be valid absolute path to directory
logdir = None
; Default directory to search for media input
; must be valid absolute path to directory
mediadir = None 

; Default blackdetect options - ffmpeg default values
[blackdetect]
; Minimum black duration: 0.01 to 3600.00
duration = 2.00
; Picture black treshold: 0.00 to 1
pic_th = 0.98
; Pixel black treshold: 0.00 to 1
pix_th = 0.10

; Default freezedetect options - ffmpeg default values
[freezedetect]
; Noise tolerance: 0 to 140
noise = 60
; Minimum silence duration: 0.01 to 3600.00
duration = 2.00

; Default silencedetect options - ffmpeg default values
[silencedetect]
; Noise tolerance: 0 to 140
noise = 60
; Minimum silence duration: 0.01 to 3600.00
duration = 2.00
; Enable mono: True or Flase - case insensitive
; defaults to Flase if no value is set
mono = False
