; Script generated by the Inno Setup Script Wizard.
; Frame Checker Setup Script
; Copyright (C) 2025 Vuk Knežević
; This installer package is distributed under the GNU General Public License (GPL-3.0)
; License Text: COPYING and LICENSE files included with the installer

#define MyAppName "Frame Checker"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Vuk Knežević"
#define MyAppURL "https://github.com/kuvk/frame-checker"
#define MyAppExeName "Frame Checker.exe"

[Setup]
AppId={{6A37C6F2-B6CE-4BAC-8CE8-79750C4D28CB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\data\resources\icon.ico
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=C:\Users\Vuk\Projects\frame-checker\resources\LICENSE.txt
SetupIconFile=C:\Users\Vuk\Projects\frame-checker\resources\icon.ico
SolidCompression=yes
WizardStyle=modern
OutputBaseFilename=frame-checker-{#MyAppVersion}-win_x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce
Name: "installffmpeg"; Description: "Install FFmpeg (required for media processing)"; GroupDescription: "Additional Tasks"; Flags: checkedonce

[Files]
Source: "C:\Users\Vuk\Projects\frame-checker\dist\main\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Vuk\Projects\frame-checker\dist\main\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Vuk\Projects\frame-checker\windows\install_ffmpeg.bat"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  UserChoice: Integer;
begin
  if (CurStep = ssPostInstall) and WizardIsTaskSelected('installffmpeg') then begin
    UserChoice := MsgBox('Setup will now install FFmpeg. Click OK to continue or Cancel to skip.', mbInformation, MB_OKCANCEL);
    if UserChoice = IDOK then begin
      if Exec(ExpandConstant('{tmp}\install_ffmpeg.bat'), '', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
        MsgBox('FFmpeg installed successfully.', mbInformation, MB_OK)
      else
        MsgBox('FFmpeg installation failed. Error code: ' + IntToStr(ResultCode), mbError, MB_OK);
    end else begin
      MsgBox('FFmpeg installation was skipped.', mbInformation, MB_OK);
    end;
  end;
end;
