# ui_widget.py - Generated by pyside6-uic from widget.ui
# Frame Checker - UI Layout
# Copyright (C) 2025 Vuk Knežević
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'widget.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QGridLayout,
    QGroupBox, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QProgressBar, QPushButton, QSizePolicy,
    QSpinBox, QTextEdit, QVBoxLayout, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(820, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        Widget.setMinimumSize(QSize(820, 600))
        self.gridLayout = QGridLayout(Widget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.main_widget = QWidget(Widget)
        self.main_widget.setObjectName(u"main_widget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy1)
        self.main_widget.setMinimumSize(QSize(820, 600))
        self.start_button = QPushButton(self.main_widget)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(660, 526, 141, 50))
        self.start_button.setMinimumSize(QSize(0, 50))
        self.start_button.setMaximumSize(QSize(16777215, 50))
        self.layoutWidget = QWidget(self.main_widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(19, 96, 781, 281))
        self.filtersVLayout = QVBoxLayout(self.layoutWidget)
        self.filtersVLayout.setSpacing(10)
        self.filtersVLayout.setObjectName(u"filtersVLayout")
        self.filtersVLayout.setContentsMargins(0, 0, 0, 0)
        self.filters_label = QLabel(self.layoutWidget)
        self.filters_label.setObjectName(u"filters_label")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.filters_label.sizePolicy().hasHeightForWidth())
        self.filters_label.setSizePolicy(sizePolicy2)

        self.filtersVLayout.addWidget(self.filters_label)

        self.filtersHLayout = QHBoxLayout()
        self.filtersHLayout.setSpacing(9)
        self.filtersHLayout.setObjectName(u"filtersHLayout")
        self.blackdetect_group = QGroupBox(self.layoutWidget)
        self.blackdetect_group.setObjectName(u"blackdetect_group")
        self.use_blackdetect = QCheckBox(self.blackdetect_group)
        self.use_blackdetect.setObjectName(u"use_blackdetect")
        self.use_blackdetect.setGeometry(QRect(10, 210, 131, 21))
        self.layoutWidget1 = QWidget(self.blackdetect_group)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 40, 238, 131))
        self.black_optionsVLayout = QVBoxLayout(self.layoutWidget1)
        self.black_optionsVLayout.setObjectName(u"black_optionsVLayout")
        self.black_optionsVLayout.setContentsMargins(0, 0, 0, 0)
        self.black_durationHLayout = QHBoxLayout()
        self.black_durationHLayout.setObjectName(u"black_durationHLayout")
        self.black_duration_label = QLabel(self.layoutWidget1)
        self.black_duration_label.setObjectName(u"black_duration_label")

        self.black_durationHLayout.addWidget(self.black_duration_label)

        self.black_duration = QDoubleSpinBox(self.layoutWidget1)
        self.black_duration.setObjectName(u"black_duration")
        sizePolicy1.setHeightForWidth(self.black_duration.sizePolicy().hasHeightForWidth())
        self.black_duration.setSizePolicy(sizePolicy1)
        self.black_duration.setMinimumSize(QSize(69, 0))
        self.black_duration.setMaximumSize(QSize(69, 16777215))
        self.black_duration.setMinimum(0.010000000000000)
        self.black_duration.setMaximum(3600.000000000000000)
        self.black_duration.setSingleStep(0.010000000000000)
        self.black_duration.setValue(2.000000000000000)

        self.black_durationHLayout.addWidget(self.black_duration)


        self.black_optionsVLayout.addLayout(self.black_durationHLayout)

        self.pic_thHLayout = QHBoxLayout()
        self.pic_thHLayout.setObjectName(u"pic_thHLayout")
        self.pic_th_label = QLabel(self.layoutWidget1)
        self.pic_th_label.setObjectName(u"pic_th_label")

        self.pic_thHLayout.addWidget(self.pic_th_label)

        self.pic_th = QDoubleSpinBox(self.layoutWidget1)
        self.pic_th.setObjectName(u"pic_th")
        sizePolicy1.setHeightForWidth(self.pic_th.sizePolicy().hasHeightForWidth())
        self.pic_th.setSizePolicy(sizePolicy1)
        self.pic_th.setMinimumSize(QSize(69, 0))
        self.pic_th.setMaximumSize(QSize(69, 16777215))
        self.pic_th.setMaximum(1.000000000000000)
        self.pic_th.setSingleStep(0.010000000000000)
        self.pic_th.setValue(0.980000000000000)

        self.pic_thHLayout.addWidget(self.pic_th)


        self.black_optionsVLayout.addLayout(self.pic_thHLayout)

        self.pix_thHLayout = QHBoxLayout()
        self.pix_thHLayout.setObjectName(u"pix_thHLayout")
        self.pix_th_label = QLabel(self.layoutWidget1)
        self.pix_th_label.setObjectName(u"pix_th_label")

        self.pix_thHLayout.addWidget(self.pix_th_label)

        self.pix_th = QDoubleSpinBox(self.layoutWidget1)
        self.pix_th.setObjectName(u"pix_th")
        sizePolicy1.setHeightForWidth(self.pix_th.sizePolicy().hasHeightForWidth())
        self.pix_th.setSizePolicy(sizePolicy1)
        self.pix_th.setMinimumSize(QSize(69, 0))
        self.pix_th.setMaximumSize(QSize(69, 16777215))
        self.pix_th.setMaximum(1.000000000000000)
        self.pix_th.setSingleStep(0.010000000000000)
        self.pix_th.setValue(0.100000000000000)

        self.pix_thHLayout.addWidget(self.pix_th)


        self.black_optionsVLayout.addLayout(self.pix_thHLayout)


        self.filtersHLayout.addWidget(self.blackdetect_group)

        self.freezedetect_group = QGroupBox(self.layoutWidget)
        self.freezedetect_group.setObjectName(u"freezedetect_group")
        self.use_freezedetect = QCheckBox(self.freezedetect_group)
        self.use_freezedetect.setObjectName(u"use_freezedetect")
        self.use_freezedetect.setGeometry(QRect(10, 210, 151, 21))
        self.layoutWidget2 = QWidget(self.freezedetect_group)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 40, 231, 91))
        self.freeze_optionsVLayout = QVBoxLayout(self.layoutWidget2)
        self.freeze_optionsVLayout.setObjectName(u"freeze_optionsVLayout")
        self.freeze_optionsVLayout.setContentsMargins(0, 0, 0, 0)
        self.freeze_noiseHLayout = QHBoxLayout()
        self.freeze_noiseHLayout.setObjectName(u"freeze_noiseHLayout")
        self.freeze_noise_label = QLabel(self.layoutWidget2)
        self.freeze_noise_label.setObjectName(u"freeze_noise_label")

        self.freeze_noiseHLayout.addWidget(self.freeze_noise_label)

        self.freeze_noise = QSpinBox(self.layoutWidget2)
        self.freeze_noise.setObjectName(u"freeze_noise")
        sizePolicy1.setHeightForWidth(self.freeze_noise.sizePolicy().hasHeightForWidth())
        self.freeze_noise.setSizePolicy(sizePolicy1)
        self.freeze_noise.setMinimumSize(QSize(69, 0))
        self.freeze_noise.setMaximumSize(QSize(69, 16777215))
        self.freeze_noise.setMaximum(140)
        self.freeze_noise.setValue(60)

        self.freeze_noiseHLayout.addWidget(self.freeze_noise)


        self.freeze_optionsVLayout.addLayout(self.freeze_noiseHLayout)

        self.freeze_durationHLayout = QHBoxLayout()
        self.freeze_durationHLayout.setObjectName(u"freeze_durationHLayout")
        self.freeze_duration_label = QLabel(self.layoutWidget2)
        self.freeze_duration_label.setObjectName(u"freeze_duration_label")

        self.freeze_durationHLayout.addWidget(self.freeze_duration_label)

        self.freeze_duration = QDoubleSpinBox(self.layoutWidget2)
        self.freeze_duration.setObjectName(u"freeze_duration")
        sizePolicy1.setHeightForWidth(self.freeze_duration.sizePolicy().hasHeightForWidth())
        self.freeze_duration.setSizePolicy(sizePolicy1)
        self.freeze_duration.setMinimumSize(QSize(69, 0))
        self.freeze_duration.setMaximumSize(QSize(69, 16777215))
        self.freeze_duration.setMinimum(0.010000000000000)
        self.freeze_duration.setMaximum(3600.000000000000000)
        self.freeze_duration.setSingleStep(0.010000000000000)
        self.freeze_duration.setValue(2.000000000000000)

        self.freeze_durationHLayout.addWidget(self.freeze_duration)


        self.freeze_optionsVLayout.addLayout(self.freeze_durationHLayout)


        self.filtersHLayout.addWidget(self.freezedetect_group)

        self.groupBox = QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(u"groupBox")
        self.use_silencedetect = QCheckBox(self.groupBox)
        self.use_silencedetect.setObjectName(u"use_silencedetect")
        self.use_silencedetect.setGeometry(QRect(10, 210, 141, 21))
        self.layoutWidget3 = QWidget(self.groupBox)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 130, 231, 41))
        self.monoHLayout = QHBoxLayout(self.layoutWidget3)
        self.monoHLayout.setObjectName(u"monoHLayout")
        self.monoHLayout.setContentsMargins(0, 0, 0, 0)
        self.enable_mono_label = QLabel(self.layoutWidget3)
        self.enable_mono_label.setObjectName(u"enable_mono_label")
        sizePolicy.setHeightForWidth(self.enable_mono_label.sizePolicy().hasHeightForWidth())
        self.enable_mono_label.setSizePolicy(sizePolicy)
        self.enable_mono_label.setMinimumSize(QSize(0, 0))

        self.monoHLayout.addWidget(self.enable_mono_label)

        self.enable_mono = QCheckBox(self.layoutWidget3)
        self.enable_mono.setObjectName(u"enable_mono")
        self.enable_mono.setMinimumSize(QSize(69, 0))
        self.enable_mono.setMaximumSize(QSize(69, 16777215))

        self.monoHLayout.addWidget(self.enable_mono)

        self.layoutWidget4 = QWidget(self.groupBox)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(10, 40, 231, 91))
        self.verticalLayout = QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.silence_noiseHLayout = QHBoxLayout()
        self.silence_noiseHLayout.setObjectName(u"silence_noiseHLayout")
        self.silence_noise_label = QLabel(self.layoutWidget4)
        self.silence_noise_label.setObjectName(u"silence_noise_label")

        self.silence_noiseHLayout.addWidget(self.silence_noise_label)

        self.silence_noise = QSpinBox(self.layoutWidget4)
        self.silence_noise.setObjectName(u"silence_noise")
        sizePolicy1.setHeightForWidth(self.silence_noise.sizePolicy().hasHeightForWidth())
        self.silence_noise.setSizePolicy(sizePolicy1)
        self.silence_noise.setMinimumSize(QSize(69, 0))
        self.silence_noise.setMaximumSize(QSize(69, 16777215))
        self.silence_noise.setMaximum(140)
        self.silence_noise.setValue(60)

        self.silence_noiseHLayout.addWidget(self.silence_noise)


        self.verticalLayout.addLayout(self.silence_noiseHLayout)

        self.silence_durationHLayout = QHBoxLayout()
        self.silence_durationHLayout.setObjectName(u"silence_durationHLayout")
        self.silence_duration_label = QLabel(self.layoutWidget4)
        self.silence_duration_label.setObjectName(u"silence_duration_label")

        self.silence_durationHLayout.addWidget(self.silence_duration_label)

        self.silence_duration = QDoubleSpinBox(self.layoutWidget4)
        self.silence_duration.setObjectName(u"silence_duration")
        sizePolicy1.setHeightForWidth(self.silence_duration.sizePolicy().hasHeightForWidth())
        self.silence_duration.setSizePolicy(sizePolicy1)
        self.silence_duration.setMinimumSize(QSize(69, 0))
        self.silence_duration.setMaximumSize(QSize(69, 16777215))
        self.silence_duration.setMinimum(0.010000000000000)
        self.silence_duration.setMaximum(3600.000000000000000)
        self.silence_duration.setSingleStep(0.010000000000000)
        self.silence_duration.setValue(2.000000000000000)

        self.silence_durationHLayout.addWidget(self.silence_duration)


        self.verticalLayout.addLayout(self.silence_durationHLayout)


        self.filtersHLayout.addWidget(self.groupBox)


        self.filtersVLayout.addLayout(self.filtersHLayout)

        self.save_status_button = QPushButton(self.main_widget)
        self.save_status_button.setObjectName(u"save_status_button")
        self.save_status_button.setGeometry(QRect(660, 453, 141, 31))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.save_status_button.sizePolicy().hasHeightForWidth())
        self.save_status_button.setSizePolicy(sizePolicy3)
        self.clear_status_button = QPushButton(self.main_widget)
        self.clear_status_button.setObjectName(u"clear_status_button")
        self.clear_status_button.setGeometry(QRect(660, 417, 141, 31))
        sizePolicy3.setHeightForWidth(self.clear_status_button.sizePolicy().hasHeightForWidth())
        self.clear_status_button.setSizePolicy(sizePolicy3)
        self.layoutWidget5 = QWidget(self.main_widget)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(19, 16, 781, 50))
        self.inputVLayout = QVBoxLayout(self.layoutWidget5)
        self.inputVLayout.setObjectName(u"inputVLayout")
        self.inputVLayout.setContentsMargins(0, 0, 0, 0)
        self.input_label = QLabel(self.layoutWidget5)
        self.input_label.setObjectName(u"input_label")

        self.inputVLayout.addWidget(self.input_label)

        self.inputHLayout = QHBoxLayout()
        self.inputHLayout.setObjectName(u"inputHLayout")
        self.input_line_edit = QLineEdit(self.layoutWidget5)
        self.input_line_edit.setObjectName(u"input_line_edit")
        self.input_line_edit.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.input_line_edit.setReadOnly(True)
        self.input_line_edit.setClearButtonEnabled(False)

        self.inputHLayout.addWidget(self.input_line_edit)

        self.file_button = QPushButton(self.layoutWidget5)
        self.file_button.setObjectName(u"file_button")

        self.inputHLayout.addWidget(self.file_button)

        self.folder_button = QPushButton(self.layoutWidget5)
        self.folder_button.setObjectName(u"folder_button")

        self.inputHLayout.addWidget(self.folder_button)


        self.inputVLayout.addLayout(self.inputHLayout)

        self.cancel_button = QPushButton(self.main_widget)
        self.cancel_button.setObjectName(u"cancel_button")
        self.cancel_button.setEnabled(False)
        self.cancel_button.setGeometry(QRect(660, 526, 141, 50))
        self.cancel_button.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.layoutWidget6 = QWidget(self.main_widget)
        self.layoutWidget6.setObjectName(u"layoutWidget6")
        self.layoutWidget6.setGeometry(QRect(19, 396, 621, 181))
        self.statusVLayout = QVBoxLayout(self.layoutWidget6)
        self.statusVLayout.setSpacing(7)
        self.statusVLayout.setObjectName(u"statusVLayout")
        self.statusVLayout.setContentsMargins(0, 0, 0, 0)
        self.status_label = QLabel(self.layoutWidget6)
        self.status_label.setObjectName(u"status_label")
        sizePolicy2.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy2)

        self.statusVLayout.addWidget(self.status_label)

        self.status = QTextEdit(self.layoutWidget6)
        self.status.setObjectName(u"status")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy4)
        self.status.setMinimumSize(QSize(0, 130))
        self.status.setMaximumSize(QSize(16777215, 130))
        self.status.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.status.setLineWrapMode(QTextEdit.LineWrapMode.NoWrap)
        self.status.setLineWrapColumnOrWidth(0)
        self.status.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)

        self.statusVLayout.addWidget(self.status)

        self.progress = QProgressBar(self.layoutWidget6)
        self.progress.setObjectName(u"progress")
        sizePolicy4.setHeightForWidth(self.progress.sizePolicy().hasHeightForWidth())
        self.progress.setSizePolicy(sizePolicy4)
        self.progress.setValue(0)

        self.statusVLayout.addWidget(self.progress)

        self.open_logs_button = QPushButton(self.main_widget)
        self.open_logs_button.setObjectName(u"open_logs_button")
        self.open_logs_button.setGeometry(QRect(660, 490, 141, 31))
        sizePolicy3.setHeightForWidth(self.open_logs_button.sizePolicy().hasHeightForWidth())
        self.open_logs_button.setSizePolicy(sizePolicy3)

        self.gridLayout.addWidget(self.main_widget, 0, 0, 1, 1)


        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Form", None))
        self.start_button.setText(QCoreApplication.translate("Widget", u"START", None))
        self.filters_label.setText(QCoreApplication.translate("Widget", u"Choose filters:", None))
        self.blackdetect_group.setTitle(QCoreApplication.translate("Widget", u"Blackdetect", None))
        self.use_blackdetect.setText(QCoreApplication.translate("Widget", u"Use blackdetect", None))
        self.black_duration_label.setText(QCoreApplication.translate("Widget", u"Minimum duration:", None))
        self.black_duration.setSuffix(QCoreApplication.translate("Widget", u"s", None))
        self.pic_th_label.setText(QCoreApplication.translate("Widget", u"Picture black threshold:", None))
        self.pix_th_label.setText(QCoreApplication.translate("Widget", u"Pixel black threshold:", None))
        self.freezedetect_group.setTitle(QCoreApplication.translate("Widget", u"Freezedetect", None))
        self.use_freezedetect.setText(QCoreApplication.translate("Widget", u"Use freezedetect", None))
        self.freeze_noise_label.setText(QCoreApplication.translate("Widget", u"Noise tolerance:", None))
        self.freeze_noise.setSuffix(QCoreApplication.translate("Widget", u"dB", None))
        self.freeze_noise.setPrefix(QCoreApplication.translate("Widget", u"-", None))
        self.freeze_duration_label.setText(QCoreApplication.translate("Widget", u"Minimum duration:", None))
        self.freeze_duration.setSuffix(QCoreApplication.translate("Widget", u"s", None))
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"Silencedetect", None))
        self.use_silencedetect.setText(QCoreApplication.translate("Widget", u"Use silencedetect", None))
        self.enable_mono_label.setText(QCoreApplication.translate("Widget", u"Enable mono:", None))
        self.enable_mono.setText("")
        self.silence_noise_label.setText(QCoreApplication.translate("Widget", u"Noise tolerance:", None))
        self.silence_noise.setSuffix(QCoreApplication.translate("Widget", u"dB", None))
        self.silence_noise.setPrefix(QCoreApplication.translate("Widget", u"-", None))
        self.silence_duration_label.setText(QCoreApplication.translate("Widget", u"Minimum duration:", None))
        self.silence_duration.setSuffix(QCoreApplication.translate("Widget", u"s", None))
        self.save_status_button.setText(QCoreApplication.translate("Widget", u" Save status log", None))
        self.clear_status_button.setText(QCoreApplication.translate("Widget", u"Clear status log", None))
        self.input_label.setText(QCoreApplication.translate("Widget", u"Choose input:", None))
        self.file_button.setText(QCoreApplication.translate("Widget", u"File", None))
        self.folder_button.setText(QCoreApplication.translate("Widget", u"Folder", None))
        self.cancel_button.setText(QCoreApplication.translate("Widget", u"CANCEL", None))
        self.status_label.setText(QCoreApplication.translate("Widget", u"Status log", None))
        self.open_logs_button.setText(QCoreApplication.translate("Widget", u"Open logs folder", None))
    # retranslateUi

